### ISSUE TITLE
Lights unavailable after updating to 0.4

### ISSUE THREAD

**Issue by excalbian** [sbidy/wiz_light#118]
Several of my lights are stuck in the "unavailable" state after restarting HA with the latest (0.4.0) release of this integration. 

* I have seen a few reports of similar behavior and tried the "enable / disable" option with no luck. 
* I'm certain the bulbs in question are online (have tested with pinging from the HA ssh session, and by connecting from the Wiz app)
* I've tested restarting HA with the bulbs on (lighted) and off (not lit, but powered)
* I also tried adding one of the affected bulbs in the UI (my bulbs are currently all defined in `config.yaml`) and the type is detected correctly, but the entity isn't created -- could this be related?
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/242196/108634187-125fe180-743e-11eb-9ade-45d686dc5b4c.png">
* The bulbs return what seems like a valid status from the command line:

```
 ~ echo '{"method":"getSystemConfig","params":{}}' | nc -u -w 1 <bulb_ip address> 38899
{"method":"getSystemConfig","env":"pro","result":{"mac":"<valid MAC>","homeId":<censored>,"roomId":<private>,"moduleName":"ESP01_SHTW1C_31","fwVersion":"1.21.2","groupId":0,"drvConf":[20,1],"ewf":[255,0,87,255,0,0,36],"ewfHex":"ff0057ff000024","ping":0}}
```

* Other wiz bulbs appear to be working correctly, so I'm not sure what's different about these (except they are the ones I want to use 😉)
* After enabling debug logging for the wiz component, I did find this in the logs:
```
Logger: homeassistant.components.light
Source: custom_components/wiz_light/light.py:225 
Integration: Light (documentation, issues) 
First occurred: 12:00:03 PM (11 occurrences) 
Last logged: 12:07:02 PM

Error adding entities for domain light with platform wiz_light
Error while setting up wiz_light platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in capability_attributes
    data[ATTR_EFFECT_LIST] = self.effect_list
  File "/config/custom_components/wiz_light/light.py", line 224, in effect_list
    return [
  File "/config/custom_components/wiz_light/light.py", line 225, in <listcomp>
    self._scenes[key]
IndexError: list index out of range
```

Please let me know if there is more I can do to help troubleshoot this issue. My python isn't great, but I've been programming for quite a while now.

**Comment by sbidy** [comment]
Ah yes - that is a bug. But this should be partly fixed with the version in the current master branch.
So can you please download/clone the current version and test again?

The problem occurs only on TW (Tunable White) bulbs because they have different light modes.

**Comment by excalbian** [comment]
Thank you!! I updated to the current `master` using HACS and the bulbs that were giving me trouble all connected just fine 😄.

I didn't even realize that these bulbs were tunable white, but that makes sense why they were affected.

**Comment by mo1seev** [comment]
I pull master branch and it still not working. When i try add lamp from GUI i have this error:

```
2021-02-28 23:21:37 ERROR (MainThread) [homeassistant.components.light] Error while setting up wiz_light platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 206, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 462, in capability_attributes
    data[ATTR_EFFECT_LIST] = self.effect_list
  File "/config/custom_components/wiz_light/light.py", line 224, in effect_list
    return [
  File "/config/custom_components/wiz_light/light.py", line 225, in <listcomp>
    self._scenes[key]
IndexError: list index out of range
```
